name: Deploy to ECR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 791918029132.dkr.ecr.us-east-1.amazonaws.com

    - name: Build Docker image
      run: docker build -t estudo .

    - name: Tag Docker image
      run: docker tag estudo:latest 791918029132.dkr.ecr.us-east-1.amazonaws.com/estudo:latest

    - name: Push Docker image to ECR
      run: docker push 791918029132.dkr.ecr.us-east-1.amazonaws.com/estudo:latest
